=== inigo/Nabbd/resources/xml/nabbd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
  <xs:element name="nabbd">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="burglary"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:decimal"/>
      <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="burglary">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="details"/>
        <xs:element ref="items"/>
      </xs:sequence>
      <xs:attribute name="reportDate" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="reportGuid" use="required"/>
      <xs:attribute name="userGuid" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="details">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="location">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="latitude"/>
        <xs:element ref="longitude"/>
        <xs:element ref="accuracy"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="latitude" type="xs:decimal"/>
  <xs:element name="longitude" type="xs:decimal"/>
  <xs:element name="accuracy" type="xs:integer"/>
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="serial"/>
        <xs:element ref="smartwater"/>
        <xs:element ref="barcode"/>
        <xs:element ref="category"/>
        <xs:element ref="price"/>
        <xs:element ref="photos"/>
      </xs:sequence>
      <xs:attribute name="itemGuid" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="serial" type="xs:integer"/>
  <xs:element name="smartwater">
    <xs:complexType mixed="true">
      <xs:attribute name="use" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="barcode">
    <xs:complexType mixed="true">
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="category" type="xs:string"/>
  <xs:element name="price" type="xs:integer"/>
  <xs:element name="photos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="photo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="photo">
    <xs:complexType>
      <xs:attribute name="dateTaken" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== inigo/Nabbd/resources/xml/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<nabbd version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nabbd.xsd">
    <burglary userGuid="123456789012345678901234567890ab" reportGuid="123456789012345678901234567890ab" reportDate="2011-03-26T01:03Z">
        <details>
            <reportedBy>Daniel Rendall</reportedBy>
            <estimatedEarliestTime>2011-03-26T01:03Z</estimatedEarliestTime>
            <estimatedLatestTime>2011-03-27T01:03Z</estimatedLatestTime>
            <latitude>45.6</latitude>
            <longitude>34.9</longitude>
            <accuracy>3</accuracy>
        </details>
        <items>
            <item itemGuid="123456789012345678901234567890ab">
                <serial>02834982542</serial>
                <smartwater use="true">1234</smartwater>
                <barcode type="upc">1234</barcode>
                <category>A category</category>
                <price type="band">1 - 100</price>
                <photos>
                    <photo dateTaken=""></photo>
                </photos>
                <notes>These are some notes</notes>
            </item>
            <item guid="123456789012345678901234567890ab">
                <serial use="true">02834982542</serial>
                <smartwater use="true"></smartwater>
                <barcode use="true" type="upc"></barcode>
                <category>A category</category>
                <price type="band">1 - 100</price>
                <photos>
                    <photo dateTaken=""></photo>
                </photos>
                <notes></notes>
            </item>
        </items>
    </burglary>
</nabbd>
